### ISSUE TITLE
为什么render会执行两次？nuclear v0.5.0

### ISSUE THREAD

**Issue by louisscrew** [AlloyTeam/Nuclear#8]
如题。
我的代码如下，非常简单的helloworld：
```
var data = {
    name:'louis'
};
var helloWorld = Nuclear.create({
    render:function(){
        console.log("render")
        return ''+
            '<div>hello,{{name}}</div>';
    }
});

new helloWorld( data, document.body);
```

用chrome调试时发现控制台中输出了两个render，既然走了两次render，那么言外之意也会走两次onfresh。这样对于一个ui庞大的SPA应用，会严重影响性能的。

当然，我不知道这是bug，还是我那个地方写的有问题。

**Comment by kmdjs** [comment]
@louisscrew 
首先这个render只是拼字符串，不是真的render，不会影响性能。但是这是一个优化的点。0.5.1版本已解决。

多谢~~~

**Comment by louisscrew** [comment]
当然，我在render函数里面写了一个console，并不是因为这个console影响性能。正是因为console执行了两次，才知道nuclear.render执行了两次。我是担心这个影响性能。希望在0.5.1能看到。

**Comment by kmdjs** [comment]
@louisscrew 0.5.1前天就发了npm啊。

**Comment by louisscrew** [comment]
@kmdjs 今天下载了0.5.1版本。这个问题确实解决了。谢谢。
